ANYNET:
  BLOCK_TYPE: res_bottleneck_block
  BOT_MULS: []
  DEPTHS: []
  GROUP_WS: []
  SE_ON: false
  SE_R: 0.25
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STRIDES: []
  WIDTHS: []
BN:
  CUSTOM_WEIGHT_DECAY: 0.0
  EPS: 1.0e-05
  MOM: 0.1
  NUM_SAMPLES_PRECISE: 1024
  USE_CUSTOM_WEIGHT_DECAY: false
  USE_PRECISE_STATS: false
  ZERO_INIT_FINAL_GAMMA: true
CFG_DEST: config.yaml
CUDNN:
  BENCHMARK: true
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: true
DIST_BACKEND: nccl
DOWNLOAD_CACHE: /tmp/pycls-download-cache
EN:
  DC_RATIO: 0.0
  DEPTHS: []
  DROPOUT_RATIO: 0.0
  EXP_RATIOS: []
  HEAD_W: 1280
  KERNELS: []
  SE_R: 0.25
  STEM_W: 32
  STRIDES: []
  WIDTHS: []
HOST: localhost
INFER:
  CUT_NUM: 1
  TOTAL_NUM: 4
LOG_DEST: file
LOG_PERIOD: 10
MEM:
  RELU_INPLACE: true
MODEL:
  DEPTH: 50
  HEADS:
    CLS_LAYER: linear
    IN_FEAT: 2048
    LOCAL_IN_FEAT: 1024
    MARGIN: 0.15
    NAME: LinearHead
    NUM_CLASSES: 1000
    POOL_LAYER: avgpool
    REDUCTION_DIM: 512
    SCALE: 30
  LOSSES:
    NAME: cross_entropy
  NUM_CLASSES: 81313
  TYPE: resnet
NUM_GPUS: 2
OPTIM:
  BASE_LR: 0.01
  DAMPENING: 0.0
  GAMMA: 0.1
  LR_MULT: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: true
  STEPS:
  - 0
  - 30
  - 60
  - 90
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
OUT_DIR: /Data_HDD/staff_xi_yang/LYMDataset/output
PORT: 12001
PREC_TIME:
  NUM_ITER: 30
  WARMUP_ITER: 3
REGNET:
  BLOCK_TYPE: res_bottleneck_block
  BOT_MUL: 1.0
  DEPTH: 10
  GROUP_W: 16
  SE_ON: false
  SE_R: 0.25
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STRIDE: 2
  W0: 32
  WA: 5.0
  WM: 2.5
RESNET:
  NUM_GROUPS: 1
  STRIDE_1X1: false
  TRANS_FUN: bottleneck_transform
  WIDTH_PER_GROUP: 64
RNG_SEED: 1
SWINTRANS:
  PRETRAINED: false
TEST:
  BATCH_SIZE: 64
  DATASET: LYMDataset
  IM_SIZE: 512
  SPLIT: clean_val.txt
  WEIGHTS: ''
TRAIN:
  AUTO_RESUME: true
  BATCH_SIZE: 64
  CHECKPOINT_PERIOD: 1
  DATASET: LYMDataset
  EVAL_PERIOD: 100
  IM_SIZE: 512
  SPLIT: clean_train.txt
  WEIGHTS: ''
