MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 81313
  HEADS:
    IN_FEAT: 2048
    LOCAL_IN_FEAT: 1024
    REDUCTION_DIM: 512
    MARGIN: 0.15
    SCALE: 30
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.01
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: train
  SPLIT: clean_train.txt
  BATCH_SIZE: 64
  IM_SIZE: 224
  EVAL_PERIOD: 100
TEST:
  DATASET: train
  SPLIT: clean_val.txt
  BATCH_SIZE: 64
  IM_SIZE: 256
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
OUT_DIR: /Data_HDD/yiming/DELG_clean_ResNet
LOG_DEST: file


INFER:
  TOTAL_NUM: 1
  CUT_NUM: 1